version: '4.0'
services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:
      - "5436:5436"
    environment:
      - POSTGRES_USER=siralf
      - POSTGRES_PASSWORD=pGreen
      - POSTGRES_DB=gokdb